language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
env:
  - CODECLIMATE_REPO_TOKEN=aebe5f2c66892e24cadf71609fcaffc3e5650322a7370283e184c58c5fd9e8a0

before_script:
  - composer self-update
  - composer install

script: phpunit --coverage-clover build/logs/clover.xml --group unit tests
after_script: ./vendor/bin/test-reporter
